name: MainWorkflow

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container Registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          email: ${{secrets.HEROKU_EMAIL}}
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: ${{secrets.HEROKU_APP_NAME}}
          dockerfile_path: ''
      - name: Set ASP.NET Environment ('Production')
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku config:set -a ${{secrets.HEROKU_APP_NAME}} ASPNETCORE_ENVIRONMENT=Production
